In [18]:
import hashlib
import pandas as pd
import os
import xml.etree.ElementTree as ET
import shutil

In [15]:
# Collect directories from the user
directories = []
print("Enter directory paths. Type 'done' when you are finished:")

while True:
    directory = input().strip()
    if directory.lower() == 'done':
        break
    # Remove surrounding quotes and spaces if they exist
    directory = directory.strip('"').strip()
    directories.append(directory)

# Create a DataFrame with the directories
df_object_dirtectories = pd.DataFrame([directories])  # Ensuring the directories are in a single row

# Define the path for saving the CSV file
csv_file_path = r'C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_CSV\object_directories.csv'

# Save to CSV without header or index
df_object_dirtectories.to_csv(csv_file_path, header=False, index=False)
df_object_dirtectories

Enter directory paths. Type 'done' when you are finished:
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo3_5.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo4.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo5_1.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo5_5.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo7_5.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo7_7.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo8_2.obj"
"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Obj\objects\objects\Avo10_3.obj"
done

,0,1,2,3,4,5,6,7
0,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...,C:\Users\15302\DART_5-10-2_2024-04-30\user_dat...

In [19]:
# Define the path to the CSV file
csv_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_CSV\All.csv"

# Read the CSV file
data_traits = pd.read_csv(csv_file_path)

# Display the DataFrame as an HTML table (automatically done in Jupyter)
data_traits

    id  Tree  CHL  CAR  ANT   EWT    PROT    CBC  Nstruct
0    1     1   24    8    5  0.01  0.0025  0.005      2.2
1    2     2   32    8    5  0.01  0.0025  0.005      2.2
2    3     3   40    8    5  0.01  0.0025  0.005      2.2
3    4     4   48    8    5  0.01  0.0025  0.005      2.2
4    5     5   56    8    5  0.01  0.0025  0.005      2.2
5    6     6   40    4    5  0.01  0.0025  0.005      2.2
6    7     7   40    6    5  0.01  0.0025  0.005      2.2
7    8     8   40    8    5  0.01  0.0025  0.005      2.2
8    9     9   40   10    5  0.01  0.0025  0.005      2.2
9   10    10   40   12    5  0.01  0.0025  0.005      2.2
10  11    11   40    8    3  0.01  0.0025  0.005      2.2
11  12    12   40    8    4  0.01  0.0025  0.005      2.2
12  13    13   40    8    5  0.01  0.0025  0.005      2.2
13  14    14   40    8    6  0.01  0.0025  0.005      2.2
14  15    15   40    8    7  0.01  0.0025  0.005      2.2
15  16    16   40    8    5  0.01  0.0025  0.003      2.2
16  17    17   40    8    5  0.01  0.0025  0.004      2.2
17  18    18   40    8    5  0.01  0.0025  0.005      2.2
18  19    19   40    8    5  0.01  0.0025  0.006      2.2
19  20    20   40    8    5  0.01  0.0025  0.007      2.2
20  21    21   40    8    5  0.01  0.0025  0.005      1.0
21  22    22   40    8    5  0.01  0.0025  0.005      1.6
22  23    23   40    8    5  0.01  0.0025  0.005      2.2
23  24    24   40    8    5  0.01  0.0025  0.005      3.0
24  25    25   40    8    5  0.01  0.0025  0.005      3.6

In [20]:
# Select columns from 'CHL' to 'Nstruct'
data_traits_filtered = data_traits.loc[:, 'CHL':'Nstruct']

# Display the filtered DataFrame
data_traits_filtered

    CHL  CAR  ANT   EWT    PROT    CBC  Nstruct
0    24    8    5  0.01  0.0025  0.005      2.2
1    32    8    5  0.01  0.0025  0.005      2.2
2    40    8    5  0.01  0.0025  0.005      2.2
3    48    8    5  0.01  0.0025  0.005      2.2
4    56    8    5  0.01  0.0025  0.005      2.2
5    40    4    5  0.01  0.0025  0.005      2.2
6    40    6    5  0.01  0.0025  0.005      2.2
7    40    8    5  0.01  0.0025  0.005      2.2
8    40   10    5  0.01  0.0025  0.005      2.2
9    40   12    5  0.01  0.0025  0.005      2.2
10   40    8    3  0.01  0.0025  0.005      2.2
11   40    8    4  0.01  0.0025  0.005      2.2
12   40    8    5  0.01  0.0025  0.005      2.2
13   40    8    6  0.01  0.0025  0.005      2.2
14   40    8    7  0.01  0.0025  0.005      2.2
15   40    8    5  0.01  0.0025  0.003      2.2
16   40    8    5  0.01  0.0025  0.004      2.2
17   40    8    5  0.01  0.0025  0.005      2.2
18   40    8    5  0.01  0.0025  0.006      2.2
19   40    8    5  0.01  0.0025  0.007      2.2
20   40    8    5  0.01  0.0025  0.005      1.0
21   40    8    5  0.01  0.0025  0.005      1.6
22   40    8    5  0.01  0.0025  0.005      2.2
23   40    8    5  0.01  0.0025  0.005      3.0
24   40    8    5  0.01  0.0025  0.005      3.6

In [21]:
# Transpose the DataFrame
data_traits_transposed = data_traits_filtered.transpose()

# Reset the index to make the transposed DataFrame cleaner and keep the variable names
data_traits_transposed.reset_index(inplace=True)

# Rename the columns appropriately
data_traits_transposed.columns = ['Variable'] + [f'Value_{i+1}' for i in range(data_traits_transposed.shape[1] - 1)]

# Display the transposed DataFrame
data_traits_transposed

,Variable,Value_1,Value_2,Value_3,Value_4,Value_5,Value_6,Value_7,Value_8,Value_9,...,Value_16,Value_17,Value_18,Value_19,Value_20,Value_21,Value_22,Value_23,Value_24,Value_25
0,CHL,24.0000,32.0000,40.0000,48.0000,56.0000,40.0000,40.0000,40.0000,40.0000,...,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000
1,CAR,8.0000,8.0000,8.0000,8.0000,8.0000,4.0000,6.0000,8.0000,10.0000,...,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000
2,ANT,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,...,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000
3,EWT,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,...,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
4,PROT,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,...,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025
5,CBC,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,...,0.0030,0.0040,0.0050,0.0060,0.0070,0.0050,0.0050,0.0050,0.0050,0.0050
6,Nstruct,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,...,2.2000,2.2000,2.2000,2.2000,2.2000,1.0000,1.6000,2.2000,3.0000,3.6000

In [22]:
# Remove the 'Variable' column
data_traits_transposed.drop(columns=['Variable'], inplace=True)

# Define the path to save the new CSV file
output_csv_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_CSV\Transposed_All.csv"

# Save to CSV without headers
data_traits_transposed.to_csv(output_csv_path, index=False, header=False)

print(f"Data saved to {output_csv_path} without headers")

Data saved to C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_CSV\Transposed_All.csv without headers

In [23]:
# Define the path where the CSV file is saved
output_csv_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_CSV\Transposed_All.csv"

# Read the CSV file
# Since the CSV does not contain headers, you might want to assign them if needed or just view without headers
data_traits_transposed = pd.read_csv(output_csv_path, header=None)

# Display the DataFrame as a table
data_traits_transposed

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,24.0000,32.0000,40.0000,48.0000,56.0000,40.0000,40.0000,40.0000,40.0000,40.0000,...,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000
1,8.0000,8.0000,8.0000,8.0000,8.0000,4.0000,6.0000,8.0000,10.0000,12.0000,...,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000
2,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,...,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000
3,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,...,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100
4,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,...,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025,0.0025
5,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,0.0050,...,0.0030,0.0040,0.0050,0.0060,0.0070,0.0050,0.0050,0.0050,0.0050,0.0050
6,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,2.2000,...,2.2000,2.2000,2.2000,2.2000,2.2000,1.0000,1.6000,2.2000,3.0000,3.6000

In [24]:
# Define the path to the XML file
xml_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Avocado_Main_Sequence_Launcher.xml"
output_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Extracted_Sequences.txt"

# Load and parse the XML file
tree = ET.parse(xml_file_path)
root = tree.getroot()

# Open the output file to write
with open(output_file_path, 'w') as file:
    # Iterate through each simulation
    for simulation in root.findall(".//Simulation"):
        sim_name = simulation.get('name')
        file.write(f"{sim_name}:\n")
        
        # Extract properties and write to file
        properties = simulation.find('Properties')
        for prop in properties.findall('Property'):
            name = prop.get('name').split('.')[-1]  # Get the last part after the dot
            value = prop.get('value')
            file.write(f"{name} = {value}\n")
        
        # Add extra newline for readability between sequences
        file.write("\n")

print(f"Data extracted and saved to {output_file_path}")

Data extracted and saved to C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Extracted_Sequences.txt

In [25]:
# Path to the original and output text files
input_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Extracted_Sequences.txt"
output_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Renamed_Extracted_Sequences.txt"

# Mapping of old names to new names
replacements = {
    'Cab =': 'CHL =',
    'Car =': 'CAR =',
    'anthocyanin =': 'ANT =',
    'Cw =': 'EWT =',
    'Cp =': 'PROT =',
    'Cbc =': 'CBC =',
    'N =': 'Nstruct =',
    'file_src =': '3D_Obj ='
}

# Read the original file
with open(input_file_path, 'r') as file:
    lines = file.readlines()

# Open the output file for writing
with open(output_file_path, 'w') as file:
    for line in lines:
        modified = False
        for key, value in replacements.items():
            if key in line:
                if key == 'file_src =':
                    # Extract only the filename without the extension from the path
                    path = line.split('=')[1].strip()
                    filename = os.path.basename(path).split('.')[0]  # Remove the extension
                    line = f'{value} {filename}\n'
                else:
                    line = line.replace(key, value)
                modified = True
                break
        # Write the modified or original line to the output file
        file.write(line)

print(f"Data modified and saved to {output_file_path}")

Data modified and saved to C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Renamed_Extracted_Sequences.txt

In [26]:
# Define the path to the input and output text files
input_file_path = 'C:/Users/15302/DART_5-10-2_2024-04-30/user_data/simulations/Avocado_Sequence/Renamed_Extracted_Sequences.txt'
output_file_path = 'C:/Users/15302/DART_5-10-2_2024-04-30/user_data/simulations/Avocado_Sequence/Trait_Structure_Extracted_Sequences.txt'

# Read the input file
with open(input_file_path, 'r') as file:
    lines = file.readlines()

# Containers for properties and traits
current_properties = {}
last_properties = {}
trait_counter = 0  # Initialize to zero, will set to 1 on the first sequence
obj_counter = {}  # To manage unique identifiers for 3D_Obj
updated_lines = []
sequence_name = ""

def properties_changed(current, last):
    # Compare relevant properties to determine if there's a change
    relevant_keys = ['CHL', 'CAR', 'ANT', 'EWT', 'PROT', 'CBC', 'Nstruct']
    for key in relevant_keys:
        if current.get(key, None) != last.get(key, None):
            return True
    return False

first_sequence = True

for line in lines:
    if "Avocado_Sequence" in line.strip():
        if current_properties:
            # For the first sequence, initialize the trait counter to 1
            if first_sequence:
                trait_counter = 1
                first_sequence = False
            else:
                if properties_changed(current_properties, last_properties):
                    trait_counter += 1  # Increment only if there's a change
            current_properties['Trait'] = trait_counter
            updated_lines.append(sequence_name + '\n')
            for prop, val in current_properties.items():
                updated_lines.append(f"{prop} = {val}\n")
            updated_lines.append('\n')
            last_properties = current_properties.copy()
            current_properties = {}
        sequence_name = line.strip()
    elif line.strip() and "=" in line:
        key, value = line.strip().split('=')
        key = key.strip()
        value = value.strip()
        current_properties[key] = value
        if key == "3D_Obj":
            if value not in obj_counter:
                obj_counter[value] = len(obj_counter) + 1  # Assign new number if not already assigned
            current_properties['OBJ'] = obj_counter[value]

# Handle the last sequence in the file
if current_properties:
    if not first_sequence and properties_changed(current_properties, last_properties):
        trait_counter += 1
    current_properties['Trait'] = trait_counter
    updated_lines.append(sequence_name + '\n')
    for prop, val in current_properties.items():
        updated_lines.append(f"{prop} = {val}\n")
    updated_lines.append('\n')

# Save the updated content to a new file
with open(output_file_path, 'w') as file:
    file.writelines(updated_lines)

print(f"Updated sequences saved to {output_file_path}")

Updated sequences saved to C:/Users/15302/DART_5-10-2_2024-04-30/user_data/simulations/Avocado_Sequence/Trait_Structure_Extracted_Sequences.txt

In [27]:
# Define paths
base_dir = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\sequence"
info_file_path = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Trait_Structure_Extracted_Sequences.txt"

# Read and parse the information file to map sequence names to OBJ and Trait
sequence_info = {}
with open(info_file_path, 'r') as file:
    content = file.readlines()
    current_sequence = None
    for line in content:
        if "Avocado_Sequence" in line:
            # Extract sequence folder name from the line
            current_sequence = line.split(':')[0].strip().split('\\')[-1]
        elif "=" in line and current_sequence:
            key, value = line.split('=')
            if key.strip() in ['OBJ', 'Trait']:
                if current_sequence not in sequence_info:
                    sequence_info[current_sequence] = {}
                sequence_info[current_sequence][key.strip()] = value.strip()

# Function to rename files in a directory based on OBJ and Trait
def rename_files(directory, obj, trait):
    for root, _, files in os.walk(directory):
        for file in files:
            filename, extension = os.path.splitext(file)
            new_filename = f"{filename}_OBJ_{obj}_Trait_{trait}{extension}"
            os.rename(os.path.join(root, file), os.path.join(root, new_filename))

# Iterate over sequence directories and rename files accordingly
for sequence in sequence_info:
    obj = sequence_info[sequence]['OBJ']
    trait = sequence_info[sequence]['Trait']
    seq_dir = os.path.join(base_dir, sequence)
    if os.path.exists(seq_dir):
        rename_files(seq_dir, obj, trait)

print("Files have been renamed based on the correct OBJ and Trait values.")

Files have been renamed based on the correct OBJ and Trait values.

In [19]:
""""
rename to orginal in xase of problem

# Define the base directory containing all sequence folders
base_dir = r"C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\sequence"

def revert_filenames(directory):
    for root, dirs, files in os.walk(directory):
        for file in files:
            # Check if file name contains the pattern
            if "_OBJ_" in file:
                original_name, _ = file.split("_OBJ_")
                extension = os.path.splitext(file)[1]
                original_full_name = f"{original_name}{extension}"
                os.rename(os.path.join(root, file), os.path.join(root, original_full_name))

# Iterate over each sequence directory and revert file names
for seq_directory in os.listdir(base_dir):
    full_path = os.path.join(base_dir, seq_directory)
    if os.path.isdir(full_path):
        revert_filenames(full_path)

print("Files have been reverted to their original names.")
"""

Files have been reverted to their original names.

In [28]:
# Define source and target directories
source_dir = r'C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\sequence'
target_dir = r'C:\Users\15302\DART_5-10-2_2024-04-30\user_data\simulations\Avocado_Sequence\Sequence_All_in_One'

# Ensure target input and output directories exist
os.makedirs(os.path.join(target_dir, 'input'), exist_ok=True)
os.makedirs(os.path.join(target_dir, 'output'), exist_ok=True)

def move_and_merge(source, destination):
    if os.path.isdir(source):
        # If source is a directory, ensure destination directory exists
        os.makedirs(destination, exist_ok=True)
        # Move all items from source to destination, merging directories
        for item in os.listdir(source):
            src_item = os.path.join(source, item)
            dest_item = os.path.join(destination, item)
            if os.path.isdir(src_item):
                # Recurse into subdirectories
                move_and_merge(src_item, dest_item)
            else:
                # Move files
                if not os.path.exists(dest_item):
                    shutil.move(src_item, dest_item)
                else:
                    # If file exists, keep both by renaming the new one
                    base, ext = os.path.splitext(dest_item)
                    count = 1
                    new_dest = f"{base}_{count}{ext}"
                    while os.path.exists(new_dest):
                        count += 1
                        new_dest = f"{base}_{count}{ext}"
                    shutil.move(src_item, new_dest)
    else:
        # Move files directly if not a directory
        if not os.path.exists(destination):
            shutil.move(source, destination)
        else:
            base, ext = os.path.splitext(destination)
            count = 1
            new_dest = f"{base}_{count}{ext}"
            while os.path.exists(new_dest):
                count += 1
                new_dest = f"{base}_{count}{ext}"
            shutil.move(source, new_dest)

# Iterate over each sequence directory and move input and output folders
for seq_name in os.listdir(source_dir):
    seq_path = os.path.join(source_dir, seq_name)
    
    # Check for input and output folders in the sequence directory
    input_path = os.path.join(seq_path, 'input')
    output_path = os.path.join(seq_path, 'output')
    
    if os.path.exists(input_path):
        # Move contents from input to the collective input folder
        move_and_merge(input_path, os.path.join(target_dir, 'input'))
    
    if os.path.exists(output_path):
        # Move contents from output to the collective output folder
        move_and_merge(output_path, os.path.join(target_dir, 'output'))

print("All input and output folders have been consolidated without removing any files.")

All input and output folders have been consolidated without removing any files.